name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEFAULT_NODE_VERSION: 20
  LATEST_NODE_VERSION: 22

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run lint
        run: npm run lint

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "refactor(github-action): auto lint"
          git push

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        if: ${{ matrix.node-version != env.LATEST_NODE_VERSION }}
        run: npm test

      - name: Run tests coverage
        if: ${{ matrix.node-version == env.LATEST_NODE_VERSION }}
        run: npm run test:coverage

      - name: Coveralls
        if: ${{ matrix.node-version == env.LATEST_NODE_VERSION }}
        uses: coverallsapp/github-action@v2
